language: java

jdk:
- oraclejdk8

sudo: false

addons:
  sonarcloud:
    organization: hekonsek-github
    token:
      secure: "sJ+xUPx5PYs9noxMBBe2AcaQWYPzQ4Yn/jW+QCwpvEqBFBSSu+d5B7yjOFriDsLbc7BJWH0VFr0ZuZKnguCqbnDg3qMXIvFqEY/884k2/NQccWPChb/p+E1jZqy1b10QstFwubTXEKusSsPe6mDdgn7ROuYP3rigTkz2Z8pfXEsPvGoBHXXjbW0clmTyFlQYW7H3dVd4LpktMsDKnDDxOJCSCaT5pIMx69YodLvvr2LQuMZe1VNasrlMgHni1Tl3Zm94/HqlsDe7iE98nYFWDb6g0tVuHeeIaeOHHUYY86nxpUaw4VR4fdffX1vVuD71rwqT/Eph9KCKdyPA9Npchd8lm/59Ab5X0ns/LkBjacsqzhjZ470L4+ihuHPO+SGQYOUs7RM3v+xQIRM0i3CoQhyJYmmxcn3jaG6sciOADSDR8CzLhgbq0gQhndQszwd7+K9XXQlZ5fV5VIj1eqs0cgDVE/fkLjrTxCs/HRsLHcfKYwIskm+gTFc8IcCxJtTOX2zuT9bK+oruaLCyEOBzz6DpI4rzAjD5uOQY4ijW4wTzgqIeuY3ucYpzO+T8lahWMRmD3MOBSfikGYjFytnhZrlkp6WkrvzilgHWrGz/1bnxAUQIoPDUhONIPYRXoN6K/uUT70qQMAEF4a0tXsZejMUhIVuVZZ71i4mSe1w7ULE="

script:
  - mvn clean install sonar:sonar -Pcoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)